---
title  : "ranger"
author : "データサイエンス関連基礎調査WG"
date   : "2023-11-09"
output :   
  word_document :
    fig_width   : 6
    fig_height  : 3
    df_print    : paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require(ranger)) install.packages('ranger')
```
***
## パッケージの概要
ランダムフォレストの高速実装で、特に高次元データに適しています。 分類木、回帰木、生存木、確率予測木のアンサンブルをサポートしています。

***
## 使用例：irisデータの分類

### Irisデータセットを読み込む
```{r}
data(iris)
head(iris)
```

### irisデータの構造
```{r}
str(iris)
```
### データセットの準備
```{r}
# データを訓練データとテストデータに分割
set.seed(123)  # 再現性のためにシードを設定
sample_indices <- sample(1:nrow(iris), 0.7 * nrow(iris))  # 70%を訓練データに使用
train_data <- iris[sample_indices, ]
test_data <- iris[-sample_indices, ]

# データサイズの確認
c(nrow(iris), nrow(train_data), nrow(test_data))
```
### モデルの生成・実行
```{r}
# モデルのトレーニング
model <- ranger(Species ~ ., data = train_data)

# テストデータでの予測
predictions <- predict(model, data = test_data)$predictions

# 予測結果と実際のクラスを比較
(confusion_matrix <- table(predictions, test_data$Species))
```